#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./apps/client

echo '🏗️👷 Styling, testing your project before committing'

# Check Prettier standards
pnpm run check-format ||
(
    echo '🤢🤮🤢🤮 
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
pnpm run check-lint ||
(
        echo '😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
pnpm run check-types ||
(
    echo '🤡😂❌🤡 
            Failed Type check. 🤡😂❌🤡'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Perfect!! committing this now. ✅✅✅✅'
